service:
  name: oif-users

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'} 
  region: us-east-1
  profile: ab3
  tracing:
    apiGateway: true
    lambda: true
  httpApi:
    payload: '2.0'
    cors: true
    authorizers:
      CognitoJwtAuthorizer:
        identitySource: $request.header.authorization
        issuerUrl: ${self:resources.Outputs.OifUserPoolProviderUrl.Value}
        audience:
        - ${self:resources.Outputs.CognitoUserPoolClientId.Value}

plugins:
  - serverless-iam-roles-per-function

functions:
  triggers_onUserMigration:
    handler: src/events/triggers.onUserMigration
    events:
      - cognitoUserPool:
          pool: OifUserPool
          trigger: UserMigration
  triggers_onPostConfirmation:
    handler: src/events/triggers/onPostConfirmation
    events:
      - cognitoUserPool:
          pool: OifUserPool
          trigger: PostConfirmation
  http_getUser:
    handler: src/events/http.getUser
    environment:
      USER_POOL_ID: ${self:resources.Outputs.OifUserPoolId.Value}
      USER_POOL_APP_CLIENT_ID: ${self:resources.Outputs.CognitoUserPoolClientId.Value}
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:*
        Resource:
          - ${self:resources.Outputs.OifUserPoolArn.Value}
    dependsOn:
      - CognitoUserPoolClient
    events:
      - httpApi:
          method: GET
          path: /api/user
          authorizer:
            name: CognitoJwtAuthorizer
  http_login:
    handler: src/events/http.login
    environment:
      USER_POOL_ID: ${self:resources.Outputs.OifUserPoolId.Value}
      USER_POOL_APP_CLIENT_ID: ${self:resources.Outputs.CognitoUserPoolClientId.Value}
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:*
        Resource:
          - ${self:resources.Outputs.OifUserPoolArn.Value}
    dependsOn:
      - CognitoUserPoolClient
    events:
      - httpApi:
          method: POST
          path: /api/users/login
  http_updateUser:
    handler: src/events/http.updateUser
    environment:
      USER_POOL_ID: ${self:resources.Outputs.OifUserPoolId.Value}
      USER_POOL_APP_CLIENT_ID: ${self:resources.Outputs.CognitoUserPoolClientId.Value}
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:*
        Resource:
          - ${self:resources.Outputs.OifUserPoolArn.Value}
    dependsOn:
      - CognitoUserPoolClient
    events:
      - httpApi:
          method: PUT
          path: /api/users
          authorizer:
            name: CognitoJwtAuthorizer
  http_register:
    handler: src/events/http.register
    environment:
      USER_POOL_ID: ${self:resources.Outputs.OifUserPoolId.Value}
      USER_POOL_APP_CLIENT_ID: ${self:resources.Outputs.CognitoUserPoolClientId.Value}
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - cognito-idp:*
        Resource:
          - ${self:resources.Outputs.OifUserPoolArn.Value}
    dependsOn:
      - CognitoUserPoolClient
    events:
      - httpApi:
          method: POST
          path: /api/users

resources:
  Resources:
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      DependsOn: CognitoUserPoolOifUserPool
      Properties:
        UserPoolId: ${self:resources.Outputs.OifUserPoolId.Value}
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
  Outputs:
    OifUserPoolProviderUrl:
      Value:
        Fn::GetAtt: 
          - CognitoUserPoolOifUserPool
          - ProviderURL
    OifUserPoolArn:
      Value:
        Fn::GetAtt:
          - CognitoUserPoolOifUserPool
          - Arn
    OifUserPoolId:
      Value: 
        Ref: CognitoUserPoolOifUserPool
    CognitoUserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
